#!/usr/bin/env sh
set -e
[ "$VERBOSE" -lt 1 ] || set -x

# Remove possibly preexisting stuff
docker-compose down -v --remove-orphans

# Build and pull images
docker-compose pull --ignore-pull-failures
docker-compose build $BUILD_FLAGS

# Check odoo bin works
docker-compose run --rm --no-deps \
    -e WAIT_DB=false -e UNACCENT=false \
    odoo --version
