#!/usr/bin/env sh
set -e
[ "$VERBOSE" -lt 1 ] || set -x

# Remove possibly preexisting stuff
docker-compose down -v --remove-orphans

# Build and pull images
docker-compose pull --ignore-pull-failures
docker-compose build $BUILD_FLAGS

# Check odoo bin works
# HACK https://github.com/docker/compose/issues/4688
docker-compose run --name "$(container-name)" --rm --no-deps \
    -e WAIT_DB=false -e UNACCENT=false \
    odoo --version
