#!/usr/bin/env sh
[ "$VERBOSE" -lt 1 ] || set -x

# Use Git Aggregator to get closed PRs
tmp="$(mktemp)"
gitaggregate -c "$REPOS_FILE" show-closed-prs 2>&1 | tee "$tmp"

# If there was output, fail
if [ -s $tmp ]; then
    exit 1
fi
