#!/usr/bin/env bash
[ "$VERBOSE" -lt 1 ] || set -x

# Use Git Aggregator to get closed PRs
tmp="$(mktemp)"
gitaggregate show-closed-prs -c "$REPOS_FILE" | tee "$tmp"

# If there was output, fail
if [ -s $tmp ]; then
    exit 1
fi
