#!/usr/bin/env python3
"""
Ensure unique and descriptive container names
"""
# TODO Remove this file & feature when fixed the following issue
# HACK https://github.com/docker/compose/issues/4688

import os
from uuid import uuid4

project = os.environ.get(
    "COMPOSE_PROJECT_NAME",
    os.path.basename(os.getcwd()))
prefix = os.environ["CONTAINER_PREFIX"]

print("{}-{}-{}".format(project, prefix, uuid4()))
