#!/usr/bin/env python3
from os import environ, makedirs
from os.path import join

PGPASSWORD = environ["PGPASSWORD"]
ADMIN_PASSWORD = environ["ADMIN_PASSWORD"]

TEMPLATES = {
    "odoo": f"ADMIN_PASSWORD={ADMIN_PASSWORD}",
    "db-creation": f"POSTGRES_PASSWORD={PGPASSWORD}",
    "db-access": f"PGPASSWORD={PGPASSWORD}",
    # Just in case you test your prod.yaml file
    "backup": "",
    "smtp": "",
}

makedirs(".docker", exist_ok=True)
for key, value in TEMPLATES.items():
    with open(join(".docker", f"{key}.env"), "w") as env_file:
        env_file.write(value)
