image: tecnativa/doodba-qa

variables:
  COMPOSE_FILE: test.yaml
  COMPOSE_PROJECT_NAME: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
  REVIEW_DOMAIN: ci.example.com

stages:
  - build
  - install
  - test
  - deploy

# Build
Pull and build images:
  stage: build
  script:
    - build

# Install
Install addons:
  stage: install
  variables:
    ADDON_CATEGORIES: "--private --extra"
  script:
    - addons-install

# Lint
Pylint loose: &pylint
  variables:
    LINT_MODE: "loose"
  script:
    - pylint

Pylint strict:
  <<: *pylint
  variables:
    LINT_MODE: "strict"
  except: &main_branches
    - ^\d+\.\d+$

Pylint strict warnings:
  <<: *pylint
  allow_failure: true
  variables:
    LINT_MODE: "strict"
  only: *main_branches

Pylint beta warnings:
  <<: *pylint
  allow_failure: true
  variables:
    LINT_MODE: "beta"

Flake8:
  script:
    - flake8

# Automated tests
Test addons:
  variables:
    ADDON_CATEGORIES: "--private --extra"
  script:
    - coverage
  coverage: /TOTAL.* (\d+)%/

# Runbot
Boot runbot:
  stage: deploy
  variables:
    DOMAIN_TEST: $CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN
  environment:
    name: review $CI_COMMIT_REF_NAME
    # TODO Reuse $DOMAIN_TEST instead
    # HACK https://gitlab.com/gitlab-org/gitlab-runner/issues/2487
    url: https://$CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN
    on_stop: Destroy runbot
  script:
    - docker-compose up -d

Destroy runbot:
  stage: deploy
  when: manual
  environment:
    name: review $CI_COMMIT_REF_NAME
    action: stop
  script:
    - destroy
