image: tecnativa/doodba-qa

variables:
  COMPOSE_FILE: test.yaml
  COMPOSE_PROJECT_NAME: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
  REVIEW_DOMAIN: ci.example.com

stages:
  - build
  - install
  - test
  - test_cleanup
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

# Build
Pull and build images:
  stage: build
  script:
    - build

Closed PRs:
  stage: build
  allow_failure: true
  script:
    - closed-prs

# Install
Install addons:
  stage: install
  variables:
    ADDON_CATEGORIES: "--private --extra --dependencies"
  script:
    - addons-install

# Lint
Pylint loose: &pylint
  variables:
    LINT_MODE: "loose"
  script:
    - pylint

Pylint strict:
  <<: *pylint
  variables:
    LINT_MODE: "strict"
  except: &main_branches
    - ^\d+\.\d+$

Pylint strict warnings:
  <<: *pylint
  allow_failure: true
  variables:
    LINT_MODE: "strict"
  only: *main_branches

Pylint beta warnings:
  <<: *pylint
  allow_failure: true
  variables:
    LINT_MODE: "beta"

Flake8:
  script:
    - flake8

# Automated tests
Test addons:
  variables:
    ADDON_CATEGORIES: "--private --extra"
  script:
    - coverage
    - mv artifacts/coverage .
  artifacts:
    paths:
      - coverage
    when: always
  coverage: /TOTAL.* (\d+)%/

# Free resources if something failed
Cleanup failed test resources:
  stage: test_cleanup
  when: on_failure
  script:
    - shutdown

# Runbot
Boot runbot:
  stage: deploy
  variables:
    DOMAIN_TEST: $CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN
  environment:
    name: review $CI_COMMIT_REF_NAME
    # TODO Reuse $DOMAIN_TEST instead
    # HACK https://gitlab.com/gitlab-org/gitlab-runner/issues/2487
    url: https://$CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN
    on_stop: Destroy runbot
  script:
    - docker-compose up -d

Destroy runbot:
  stage: deploy
  when: manual
  environment:
    name: review $CI_COMMIT_REF_NAME
    action: stop
  script:
    - destroy

Push docker image:
  stage: deploy
  only:
    - /^\d+\.\d+$/
  script:
    - docker-compose push
