#!/usr/bin/env bash
set -e
[ "$VERBOSE" -lt 1 ] || set -x

# Check addons exist
addons="$(addons list -i $ADDON_CATEGORIES)" || exit 0

# Create DB if needed
[ "$ODOO_VERSION" != 8.0 ] || createdb

# Install all required addons
addons init $ADDON_CATEGORIES
