#!/usr/bin/env bash
[ "$VERBOSE" -lt 1 ] || set -x

# Check addons exist
returncode=0
addons="$(addons list -ix $ADDON_CATEGORIES)" || returncode=$?

# If no addons are found, it's done
[ "$returncode" -eq 2 ] && exit 0 || [ "$returncode" -eq 0 ]

# Activate insider dependencies
source /qa/venv/bin/activate

# Test addons and report coverage
odoo="$(realpath "$(which odoo)")"
cd
coverage run \
    --source "$(addons list -ixf $ADDON_CATEGORIES)" \
    --omit '*/__openerp__.py,*/__manifest__.py,/opt/odoo/custom/src/*/*/__init__.py' \
    "$odoo" --stop-after-init --workers 0 --test-enable --init "$addons"
returncode=$?
coverage report --skip-covered
mkdir -p /qa/artifacts/coverage
coverage html --skip-covered --directory /qa/artifacts/coverage
exit $returncode
