#!/usr/bin/env bash
set -e
[ "$VERBOSE" -lt 1 ] || set -x

# Check addons exist
errorcode=0
addons="$(addons list -ifxs ' ' $ADDON_CATEGORIES)" || errorcode=$?

# If no addons are found, it's done
[ "$errorcode" -eq 4 ] && exit 0 || [ "$errorcode" -eq 0 ]

# Activate insider dependencies
source /qa/venv/bin/activate
cd /qa
export PATH="$PATH:/qa/mqt/travis"

# Lint
export INCLUDE_LINT="$addons"
test_flake8
