#!/usr/bin/env bash
set -e
[ "$VERBOSE" -lt 1 ] || set -x

# Check addons exist
addons="$(addons list -fs ' ' $ADDON_CATEGORIES)" || failed=1
if [ "$failed" == "1" ]; then
    exit 0
fi

# Dependencies
cd "$(mktemp -d)"
git clone -q --depth 1 https://github.com/OCA/maintainer-quality-tools.git .
pip install -q --user flake8
export PATH="$PATH:$(pwd)/travis"

# Put all addons to lint into same parent folder
cd "$(mktemp -d)"
ln -s $addons .

# Lint
test_flake8
