#!/usr/bin/env bash
set -e
[ "$VERBOSE" -lt 1 ] || set -x

# Check addons exist
INCLUDE_LINT="$(addons list -ifs ' ' $ADDON_CATEGORIES)" || exit 0
export INCLUDE_LINT

# Dependencies
cd "$(mktemp -d)"
git clone -q --depth 1 https://github.com/OCA/maintainer-quality-tools.git .
pip install -q --user flake8
export PATH="$PATH:$(pwd)/travis"

# Lint
test_flake8
