#!/usr/bin/env bash
set -e
[ "$VERBOSE" -lt 1 ] || set -x

# Configure pylint
addons="$(addons list -ifxs ' ' $ADDON_CATEGORIES)" || exit 0
if [ -n "$LINT_ENABLE" ]; then
    enable="--enable $LINT_ENABLE"
fi
if [ -n "$LINT_DISABLE" ]; then
    disable="--disable $LINT_DISABLE"
fi

# Activate insider dependencies
venv="/qa/py$(python -c 'import sys; print(sys.version[0])')"
source $venv/bin/activate
cd /qa/mqt

# Lint
# TODO Use MQT's `test_pylint` directly when it becomes more reusable
code=0
for addon in $addons; do
    pylint --load-plugins pylint_odoo \
        --rcfile /qa/mqt/travis/cfg/$PYLINT_CONFIG_FILE \
        --valid_odoo_versions=$ODOO_VERSION \
        $enable $disable $addon || code=$?
done

exit $code
